version: "3"
services:
  chrome:
    image: selenium/node-chrome:beta
    container_name: selenium-chrome
    shm_size: 2gb
    links:
      - selenium-hub:selenium-hub
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    environment:
      - SE_NODE_SESSION_TIMEOUT=-1
    ports:
      - "4444:4444"

