version: "3"
services:
  chrome:
    image: selenium/node-chrome
    container_name: selenium-chrome
    ports:
      - "5900"
    shm_size: 4gb
    links:
      - selenium-hub:selenium-hub
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_SESSION_TIMEOUT=5
      - JAVA_OPTS=-XX:ActiveProcessorCount=10 -Xmx3g

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"

